// app/javascript/react_components/Lists.js
import React from "react"
import List from "./List";
import NewList from "./NewList";
import * as APIs from '../apis.js'
class Lists extends React.Component {
  
  constructor(props) {
    super(props);
    console.log("Lists Component");
    console.log(props);
    this.state = {
      lists: []
    };
    this.fetchLists = this.fetchLists.bind(this);
    this.setLists = this.setLists.bind(this);
    this.handleCreate = this.handleCreate.bind(this);
    /*this.handleUpdate = this.handleUpdate.bind(this);
    this.handleDelete = this.handleDelete.bind(this);*/
  }

  componentDidMount() {
    this.fetchLists()
  }

  fetchLists() {
    APIs.fetchLists(this.setLists)
  }

  setLists(lists) {
    this.setState({ lists: lists })
  }

  handleCreate(list) {
    APIs.createList(list, this.fetchLists)
  }

  render () {
    return (
      <div className="lists">
        {this.state.lists.map((list) => {
            return(
              <React.Fragment key={list.id}>
                <List list={list} />
                <hr/>
              </React.Fragment>
            )
          })}
        <NewList handleCreate={this.handleCreate} />
      </div>
    );
  }
}

export default Lists

// app/javascript/components/Lists.vue
<template>
  <div class="lists">
    <template v-for="list in lists">
      <List v-bind:list="list" v-bind:key="list.id" />
      <hr v-bind:key="'hr-'+list.id" />
    </template>
    <button>New List</button>
  </div>
</template>

<script>
import List from './List.vue'
import * as APIs from '../apis.js'
export default {
  components: {
    List
  },

  data: function () {
    return {
      lists : []
    }
  },

  mounted: function () {
    console.log("**Lists MOUNTED**")
    console.log(this)
    APIs.fetchLists(this.setLists)
  },

  methods: {
    setLists(lists) {
      this.lists = lists
    },
  }
}
</script>

<style scoped>
</style>
