// app/javascript/vue_components/NewList.vue
<template>
  <div v-if="creating" class="list">
    <input class="name" v-model="list.name" />
    <button v-on:click="$emit('create', list); creating=false">Create</button>
    <button v-on:click="creating=false">Cancel</button>
  </div>
  <div v-else class="list">
    <button v-on:click="creating=true">New List</button>
  </div>
</template>

<script>
export default {
  data: function () {
    return {
      creating: false,
      list: {}
    }
  }
}
</script>

<style scoped>
</style>

// app/javascript/react_components/NewList.js
import React from "react"
class NewList extends React.Component {

  constructor(props) {
    super(props);
    console.log("NewList");
    console.log(props)
    this.state = {
      creating: false
    }
    this.toggleCreating = this.toggleCreating.bind(this)
    this.handleCreate = this.handleCreate.bind(this)
  }

  toggleCreating() {
    this.setState({creating: !this.state.creating})
  }

  handleCreate() {
    this.props.handleCreate({
      name: this.name.value
    })
    this.toggleCreating();
  }

  render() {
    let name = this.state.creating ? <input className="name" type="text" ref={input => this.name = input} /> : "";
    let createButton = this.state.creating ? <button onClick={() => this.handleCreate()}>Create</button> : "";
    return (
      <div className="new-list">
        {name}
        {createButton}
        <button onClick={() => this.toggleCreating()}>{this.state.creating ? 'Cancel' : 'New List'}</button>
      </div>
    );
  }

}

export default NewList
