// app/javascript/vue_components/NewTask.vue
<template>
  <div v-if="creating" v-bind="attrs">
    <input class="done" type="checkbox" v-model="task.done" />
    <input class="priority" type="number" v-model="task.priority" />
    <input class="name" v-model="task.name" />
    <button v-on:click="$emit('create', task); creating=false">Create</button>
    <button v-on:click="creating=false">Cancel</button>
  </div>
  <div v-else v-bind="attrs">
    <button v-on:click="creating=true">New Task</button>
  </div>
</template>

<script>
export default {
  data: function () {
    return {
      creating: false,
      task: {}
    }
  },

  computed: {
    attrs: function() {
      return this.task.done ? { class: "task completed" } : { class: "task" }
    }
  }
}
</script>

<style scoped>
</style>

// app/javascript/react_components/NewTask.js
import React from "react"
class NewTask extends React.Component {

  constructor(props) {
    super(props);
    console.log("NewTask");
    console.log(props)
    this.state = {
      creating: false
    }
    this.toggleCreating = this.toggleCreating.bind(this)
    this.handleCreate = this.handleCreate.bind(this)
  }

  toggleCreating() {
    this.setState({creating: !this.state.creating})
  }

  handleCreate() {
    this.props.handleCreate({
      done: this.done.checked, 
      priority: this.priority.value, 
      name: this.name.value
    })
    this.toggleCreating();
  }

  render() {
    let done = this.state.creating ? <input className="done" type="checkbox" ref={input => this.done = input} /> : "";
    let priority = this.state.creating ? <input className="priority" type="number" ref={input => this.priority = input} /> : "";
    let name = this.state.creating ? <input className="name" type="text" ref={input => this.name = input} /> : "";
    let createButton = this.state.creating ? <button onClick={() => this.handleCreate()}>Create</button> : "";
    return (
      <div className="task">
        {done}
        {priority}
        {name}
        {createButton}
        <button onClick={() => this.toggleCreating()}>{this.state.creating ? 'Cancel' : 'New Task'}</button>
      </div>
    );
  }

}

export default NewTask
